[package]
name = "events"
version = "0.1.0"
edition = "2021"
authors = ["Jesse Greenough"]
description = ""

[dependencies]
tokio = { version = "1.43.0", features = ["rt-multi-thread", "sync", "macros", "time"] }
tokio-test = "0.4.4"
dashmap = "7.0.0-rc1"
futures = "0.3.31"